Pub/Sub: raise exceptions when invalid id
kernelci/kernelci-api pull request #105
Opened 2022-01-26 21:25 UTC by gctucker

Raise a `ValueError` exception when the subscription id is not valid.

Depends on #99

2022-01-31 11:12 UTC, JenySadadia requested changes
We also need to catch ValueError in `listen` endpoint.

```
@app.get('/listen/{sub_id}')
async def listen(sub_id: int, user: User = Depends(get_user)):
    try:
        msg = await pubsub.listen(sub_id)
        if msg is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Not subscribed to channel with id: {sub_id}"
            )
        return msg
    except ValueError as error:
        raise HTTPException(
                status_code=status.HTTP_204_NO_CONTENT,
                detail=str(error)
        )
```

2022-02-01 12:15 UTC, gctucker commented
> We also need to catch ValueError in `listen` endpoint.
> 
> ```
> @app.get('/listen/{sub_id}')
> async def listen(sub_id: int, user: User = Depends(get_user)):
>     try:
>         msg = await pubsub.listen(sub_id)
>         if msg is None:
>             raise HTTPException(
>                 status_code=status.HTTP_404_NOT_FOUND,
>                 detail=f"Not subscribed to channel with id: {sub_id}"
>             )
>         return msg
>     except ValueError as error:
>         raise HTTPException(
>                 status_code=status.HTTP_204_NO_CONTENT,
>                 detail=str(error)
>         )
> ```

OK I've added that and updated unit tests accordingly.

2022-02-02 21:08 UTC, gctucker commented
@JenySadadia Could you please take another look?

2022-02-03 05:21 UTC, JenySadadia requested changes

2022-02-03 05:21 UTC, JenySadadia commented on test/test_listen_handler.py
> +    mock_listen.return_value = None
We can omit `mock_listen` from this.

```
def test_listen_endpoint_without_token(mock_get_current_user,
                                       mock_init_sub_id):
    """
    Test Case : Test KernelCI API GET /listen endpoint for the
    negative path
    Expected Result :
        HTTP Response Code 401 Unauthorized
        The request requires user authentication by token in header
    """
    user = User(username='bob',
                hashed_password='$2b$12$CpJZx5ooxM11bCFXT76/z.o6HWs2sPJy4iP8.'
                                'xCZGmM8jWXUXJZ4K',
                active=True)
    mock_get_current_user.return_value = user

    with TestClient(app) as client:
        response = client.get(
            "/listen/1",
            headers={
                "Accept": "application/json"
            },
        )
        assert response.status_code == 401
```

2022-02-03 05:21 UTC, JenySadadia commented on test/test_listen_handler.py
>  def test_listen_endpoint_not_found(mock_get_current_user,
We can add another assert statement to endpoint `test_listen_endpoint_not_found`:
```
assert 'detail' in response.json()
```

2022-02-07 05:16 UTC, JenySadadia approved these changes

2022-02-08 10:10 UTC, merged