pyproject.toml: add package directories such as templates and scripts
kernelci/kernelci-api pull request #481
Opened 2024-02-19 12:11 UTC by JenySadadia

Only the `api` directory is included with the python package atm. Add directories such as templates and scripts to run API container properly to the package.

2024-02-19 12:48 UTC, pawiecz requested changes

2024-02-19 12:48 UTC, pawiecz commented on pyproject.toml
> +templates = ["*.jinja2"]
```suggestion
templates = ["*.jinja2", "*.html"]
```

See https://github.com/kernelci/kernelci-api/pull/458

2024-02-19 12:56 UTC, JenySadadia commented on pyproject.toml
> +templates = ["*.jinja2"]
Resolved. Thanks.

2024-02-19 13:00 UTC, JenySadadia commented
Instead of using `[tool.setuptools.package-data]` I could have added `include_package_data = true` flag and that would include all the non-py files of the directory but then we would lose control over what is being shared in the package.

2024-02-19 13:06 UTC, pawiecz approved these changes
Verified with imported `templates/viewer.html` from #458:

```sh
$ pip install .
$ pip show -f kernelci-api
Files:
(snip)
  scripts/setup_admin_user
  templates/email-verification-successful.jinja2
  templates/email-verification.jinja2
  templates/reset-password-successful.jinja2
  templates/reset-password.jinja2
  templates/viewer.html
```

2024-02-20 09:33 UTC, nuclearcat commented
It works, thanks!

2024-02-20 09:34 UTC, merged