Initial API unit test case - Root endpoint
kernelci/kernelci-api pull request #51
Opened 2021-12-15 04:53 UTC by JenySadadia

Fixes https://github.com/kernelci/kernelci-api/issues/36

api/test_api.py : Add test for root endpoint using fastapi TestClient
docker/api/requirements-dev.txt : Add pytest and fastapi

Signed-off-by: Jeny Sadadia <jeny.sadadia@gmail.com>

2021-12-15 09:55 UTC, mgalka commented
@JenySadadia Does this work for you?
I installed packages from requirements.txt and requirements-dev.txt
I tried running it with
```
pytest api
```
and I'm getting errors

```
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/mgalka/projects/kernelci/kernelci-api
collected 0 items / 1 error                                                                                                                                                                           

=============================================================================================== ERRORS ================================================================================================
__________________________________________________________________________________ ERROR collecting api/test_api.py ___________________________________________________________________________________
api/test_api.py:7: in <module>
    from .main import app
api/main.py:16: in <module>
    auth = Authentication(db)
api/auth.py:35: in __init__
    self._settings = Settings()
pydantic/env_settings.py:36: in pydantic.env_settings.BaseSettings.__init__
    ???
pydantic/main.py:406: in pydantic.main.BaseModel.__init__
    ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for Settings
E   secret_key
E     field required (type=value_error.missing)
```

2021-12-15 09:58 UTC, JenySadadia commented
Hi @mgalka ,
You need to export .env file with SECRET_KEY.
This would work after that.

2021-12-15 11:00 UTC, mgalka requested changes
A few minor things in the code. 

Apart from that it'll be good to add a section in README on how to run tests.

2021-12-15 11:00 UTC, mgalka commented on api/test_api.py
> +    assert response.json() == {"message": "KernelCI API"}
We will probably need an instance of the `TestClient` in a few places so it maybe worth creating a fixture out of it.

```suggestion
@pytest.fixture
def client():
    return TestClient(app)


def test_root_endpoint(client):
    """
    Test Case : Test KernelCI API root endpoint
    Expected Result :
        HTTP Response Code 200 OK
        JSON with 'message' key
    """
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "KernelCI API"}
```

2021-12-15 11:23 UTC, JenySadadia commented on docker/api/requirements-dev.txt
> +pytest==6.2.5
How about we use a shell script to install all the packages?
I have committed file ``` installPackages.sh ```
Please review.

2021-12-16 04:04 UTC, JenySadadia commented on docker/api/requirements-dev.txt
> +pytest==6.2.5
We can have one shell script to setup prod env and another one for dev env.

2021-12-16 11:41 UTC, mgalka approved these changes
Looks good to me

2021-12-16 12:55 UTC, merged